
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
#     here stars amigo part
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

#  kafka:
#    image: confluentinc/cp-kafka
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#    ports:
#      - "9092:9092"
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
#  user-service:
#    build: ./user-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#
#  question-service:
#    build: ./question-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - postgres
#
#  test-service:
#    build: ./test-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - postgres
#      - kafka
#
#  result-service:
#    build: ./result-service
#    ports:
#      - "8084:8084"
#    depends_on:
#      - postgres
#      - kafka
